name: Node.js CI

on:
  workflow_dispatch:  # Allows manual trigger of the workflow

  push:
    branches:
      - main  # Trigger deployment on pushes to the main branch

    paths:
      - 'src/**'  # Only trigger on changes to the src directory
      - 'package.json'  # Also trigger on changes to package.json

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [22.14.x]

        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: 'npm'
                  cache-dependency-path: package-lock.json

            - name: Run CI command
              run: npm ci

            # - name: Check linting
            #   run: npm run lint
            
            # - name: Run the tests
            #   run: npm run test

            - name: Build
              run: npm run build