name: Deploy to AWS

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: prod

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2

    - name: Package Lambda Code
      run: |
        zip -r index.zip aws/index.js
        aws s3 cp index.zip s3://lorelibrary-deployment-artifacts/

    - name: Deploy CloudFormation Stack
      run: |
        aws cloudformation deploy \ 
          --template-file aws/stack.yml \
          --stack-name lorelibrary-stack \
          --capabilities CAPABILITY_NAMED_IAM \
          --parameter-overrides LambdaCodeS3Bucket=lorelibrary-deployment-artifacts LambdaCodeS3Key=index.zip